import { Player } from './types';

// ─── IPL 2026 Squad Data ────────────────────────────────────────────────────
// Roles: BAT = Batsman, BOWL = Bowler, AR = All-Rounder, WK = Wicket-Keeper

export const ALL_PLAYERS: Player[] = [
  // ── CSK – Chennai Super Kings ──────────────────────────────────────────────
  { id: 'csk-gaikwad',      name: 'Ruturaj Gaikwad',      team: 'CSK', role: 'BAT'  },
  { id: 'csk-dhoni',         name: 'MS Dhoni',              team: 'CSK', role: 'WK'   },
  { id: 'csk-samson',        name: 'Sanju Samson',          team: 'CSK', role: 'WK'   },
  { id: 'csk-brevis',        name: 'Dewald Brevis',         team: 'CSK', role: 'BAT'  },
  { id: 'csk-mhatre',        name: 'Ayush Mhatre',          team: 'CSK', role: 'BAT'  },
  { id: 'csk-sarfaraz',      name: 'Sarfaraz Khan',         team: 'CSK', role: 'BAT'  },
  { id: 'csk-urvil',         name: 'Urvil Patel',           team: 'CSK', role: 'WK'   },
  { id: 'csk-kartik',        name: 'Kartik Sharma',         team: 'CSK', role: 'WK'   },
  { id: 'csk-dube',          name: 'Shivam Dube',           team: 'CSK', role: 'AR'   },
  { id: 'csk-ashwin',        name: 'Ravichandran Ashwin',   team: 'CSK', role: 'AR'   },
  { id: 'csk-anshul',        name: 'Anshul Kamboj',         team: 'CSK', role: 'AR'   },
  { id: 'csk-ghosh',         name: 'Ramakrishna Ghosh',     team: 'CSK', role: 'AR'   },
  { id: 'csk-veer',          name: 'Prashant Veer',         team: 'CSK', role: 'AR'   },
  { id: 'csk-aman',          name: 'Aman Khan',             team: 'CSK', role: 'AR'   },
  { id: 'csk-short',         name: 'Matthew Short',         team: 'CSK', role: 'AR'   },
  { id: 'csk-khaleel',       name: 'Khaleel Ahmed',         team: 'CSK', role: 'BOWL' },
  { id: 'csk-noorahmad',     name: 'Noor Ahmad',            team: 'CSK', role: 'BOWL' },
  { id: 'csk-mukesh',        name: 'Mukesh Choudhary',      team: 'CSK', role: 'BOWL' },
  { id: 'csk-spencer',       name: 'Spencer Johnson',       team: 'CSK', role: 'BOWL' },
  { id: 'csk-shreyas-gopal', name: 'Shreyas Gopal',         team: 'CSK', role: 'BOWL' },
  { id: 'csk-matt-henry',    name: 'Matt Henry',            team: 'CSK', role: 'BOWL' },
  { id: 'csk-rahul-chahar',  name: 'Rahul Chahar',          team: 'CSK', role: 'BOWL' },
  { id: 'csk-foulkes',       name: 'Zakary Foulkes',        team: 'CSK', role: 'BOWL' },
  { id: 'csk-overton',       name: 'Jamie Overton',         team: 'CSK', role: 'BOWL' },
  { id: 'csk-gurjapneet',    name: 'Gurjapneet Singh',      team: 'CSK', role: 'BOWL' },
  { id: 'csk-hosein',        name: 'Akeal Hosein',          team: 'CSK', role: 'BOWL' },

  // ── MI – Mumbai Indians ────────────────────────────────────────────────────
  { id: 'mi-hardik',         name: 'Hardik Pandya',         team: 'MI',  role: 'AR'   },
  { id: 'mi-rohit',          name: 'Rohit Sharma',          team: 'MI',  role: 'BAT'  },
  { id: 'mi-surya',          name: 'Suryakumar Yadav',      team: 'MI',  role: 'BAT'  },
  { id: 'mi-tilak',          name: 'Tilak Varma',           team: 'MI',  role: 'BAT'  },
  { id: 'mi-qdk',            name: 'Quinton de Kock',       team: 'MI',  role: 'WK'   },
  { id: 'mi-rickelton',      name: 'Ryan Rickelton',        team: 'MI',  role: 'WK'   },
  { id: 'mi-minz',           name: 'Robin Minz',            team: 'MI',  role: 'WK'   },
  { id: 'mi-jacks',          name: 'Will Jacks',            team: 'MI',  role: 'AR'   },
  { id: 'mi-santner',        name: 'Mitchell Santner',      team: 'MI',  role: 'AR'   },
  { id: 'mi-rutherford',     name: 'Sherfane Rutherford',   team: 'MI',  role: 'AR'   },
  { id: 'mi-shardul',        name: 'Shardul Thakur',        team: 'MI',  role: 'AR'   },
  { id: 'mi-naman',          name: 'Naman Dhir',            team: 'MI',  role: 'AR'   },
  { id: 'mi-bawa',           name: 'Raj Angad Bawa',        team: 'MI',  role: 'AR'   },
  { id: 'mi-bosch',          name: 'Corbin Bosch',          team: 'MI',  role: 'AR'   },
  { id: 'mi-ankolekar',      name: 'Atharva Ankolekar',     team: 'MI',  role: 'AR'   },
  { id: 'mi-bumrah',         name: 'Jasprit Bumrah',        team: 'MI',  role: 'BOWL' },
  { id: 'mi-boult',          name: 'Trent Boult',           team: 'MI',  role: 'BOWL' },
  { id: 'mi-deepak-chahar',  name: 'Deepak Chahar',         team: 'MI',  role: 'BOWL' },
  { id: 'mi-markande',       name: 'Mayank Markande',       team: 'MI',  role: 'BOWL' },
  { id: 'mi-ghazanfar',      name: 'Allah Ghazanfar',       team: 'MI',  role: 'BOWL' },
  { id: 'mi-ashwani',        name: 'Ashwani Kumar',         team: 'MI',  role: 'BOWL' },
  { id: 'mi-rawat',          name: 'Mayank Rawat',          team: 'MI',  role: 'BAT'  },
  { id: 'mi-malewar',        name: 'Danish Malewar',        team: 'MI',  role: 'BAT'  },
  { id: 'mi-izhar',          name: 'Mohammad Izhar',        team: 'MI',  role: 'BOWL' },
  { id: 'mi-raghu',          name: 'Raghu Sharma',          team: 'MI',  role: 'BOWL' },

  // ── RCB – Royal Challengers Bengaluru ─────────────────────────────────────
  { id: 'rcb-kohli',         name: 'Virat Kohli',           team: 'RCB', role: 'BAT'  },
  { id: 'rcb-patidar',       name: 'Rajat Patidar',         team: 'RCB', role: 'BAT'  },
  { id: 'rcb-salt',          name: 'Phil Salt',             team: 'RCB', role: 'WK'   },
  { id: 'rcb-padikkal',      name: 'Devdutt Padikkal',      team: 'RCB', role: 'BAT'  },
  { id: 'rcb-jitesh',        name: 'Jitesh Sharma',         team: 'RCB', role: 'WK'   },
  { id: 'rcb-jordan-cox',    name: 'Jordan Cox',            team: 'RCB', role: 'WK'   },
  { id: 'rcb-krunal',        name: 'Krunal Pandya',         team: 'RCB', role: 'AR'   },
  { id: 'rcb-venkatesh',     name: 'Venkatesh Iyer',        team: 'RCB', role: 'AR'   },
  { id: 'rcb-shepherd',      name: 'Romario Shepherd',      team: 'RCB', role: 'AR'   },
  { id: 'rcb-bethell',       name: 'Jacob Bethell',         team: 'RCB', role: 'AR'   },
  { id: 'rcb-swapnil',       name: 'Swapnil Singh',         team: 'RCB', role: 'AR'   },
  { id: 'rcb-bhuvi',         name: 'Bhuvneshwar Kumar',     team: 'RCB', role: 'BOWL' },
  { id: 'rcb-hazlewood',     name: 'Josh Hazlewood',        team: 'RCB', role: 'BOWL' },
  { id: 'rcb-yash-dayal',    name: 'Yash Dayal',            team: 'RCB', role: 'BOWL' },
  { id: 'rcb-thushara',      name: 'Nuwan Thushara',        team: 'RCB', role: 'BOWL' },
  { id: 'rcb-suyash',        name: 'Suyash Sharma',         team: 'RCB', role: 'BOWL' },
  { id: 'rcb-rasikh',        name: 'Rasikh Salam',          team: 'RCB', role: 'BOWL' },
  { id: 'rcb-duffy',         name: 'Jacob Duffy',           team: 'RCB', role: 'BOWL' },
  { id: 'rcb-abhinandan',    name: 'Abhinandan Singh',      team: 'RCB', role: 'BOWL' },
  { id: 'rcb-mangesh',       name: 'Mangesh Yadav',         team: 'RCB', role: 'BOWL' },
  { id: 'rcb-ostwal',        name: 'Vicky Ostwal',          team: 'RCB', role: 'BOWL' },
  { id: 'rcb-tim-david',     name: 'Tim David',             team: 'RCB', role: 'BAT'  },
  { id: 'rcb-vihaan',        name: 'Vihaan Malhotra',       team: 'RCB', role: 'BAT'  },
  { id: 'rcb-satvik',        name: 'Satvik Deswal',         team: 'RCB', role: 'BAT'  },
  { id: 'rcb-kanishk',       name: 'Kanishk Chouhan',       team: 'RCB', role: 'BAT'  },

  // ── KKR – Kolkata Knight Riders ───────────────────────────────────────────
  { id: 'kkr-rinku',         name: 'Rinku Singh',           team: 'KKR', role: 'BAT'  },
  { id: 'kkr-narine',        name: 'Sunil Narine',          team: 'KKR', role: 'AR'   },
  { id: 'kkr-russell',       name: 'Andre Russell',         team: 'KKR', role: 'AR'   },
  { id: 'kkr-cameron-green', name: 'Cameron Green',         team: 'KKR', role: 'AR'   },
  { id: 'kkr-rachin',        name: 'Rachin Ravindra',       team: 'KKR', role: 'AR'   },
  { id: 'kkr-ramandeep',     name: 'Ramandeep Singh',       team: 'KKR', role: 'AR'   },
  { id: 'kkr-anukul',        name: 'Anukul Roy',            team: 'KKR', role: 'AR'   },
  { id: 'kkr-gurbaz',        name: 'Rahmanullah Gurbaz',    team: 'KKR', role: 'WK'   },
  { id: 'kkr-seifert',       name: 'Tim Seifert',           team: 'KKR', role: 'WK'   },
  { id: 'kkr-rahane',        name: 'Ajinkya Rahane',        team: 'KKR', role: 'BAT'  },
  { id: 'kkr-manish',        name: 'Manish Pandey',         team: 'KKR', role: 'BAT'  },
  { id: 'kkr-angkrish',      name: 'Angkrish Raghuvanshi',  team: 'KKR', role: 'BAT'  },
  { id: 'kkr-finn-allen',    name: 'Finn Allen',            team: 'KKR', role: 'BAT'  },
  { id: 'kkr-powell',        name: 'Rovman Powell',         team: 'KKR', role: 'BAT'  },
  { id: 'kkr-tripathi',      name: 'Rahul Tripathi',        team: 'KKR', role: 'BAT'  },
  { id: 'kkr-varun',         name: 'Varun Chakaravarthy',   team: 'KKR', role: 'BOWL' },
  { id: 'kkr-pathirana',     name: 'Matheesha Pathirana',   team: 'KKR', role: 'BOWL' },
  { id: 'kkr-umran',         name: 'Umran Malik',           team: 'KKR', role: 'BOWL' },
  { id: 'kkr-vaibhav-arora', name: 'Vaibhav Arora',         team: 'KKR', role: 'BOWL' },
  { id: 'kkr-saini',         name: 'Navdeep Saini',         team: 'KKR', role: 'BOWL' },
  { id: 'kkr-muzarabani',    name: 'Blessing Muzarabani',   team: 'KKR', role: 'BOWL' },
  { id: 'kkr-kartik-tyagi',  name: 'Kartik Tyagi',          team: 'KKR', role: 'BOWL' },
  { id: 'kkr-solanki',       name: 'Prashant Solanki',      team: 'KKR', role: 'BOWL' },
  { id: 'kkr-tejasvi',       name: 'Tejasvi Singh',         team: 'KKR', role: 'BOWL' },
  { id: 'kkr-sarthak',       name: 'Sarthak Ranjan',        team: 'KKR', role: 'BAT'  },

  // ── DC – Delhi Capitals ───────────────────────────────────────────────────
  { id: 'dc-kl-rahul',       name: 'KL Rahul',              team: 'DC',  role: 'WK'   },
  { id: 'dc-axar',           name: 'Axar Patel',            team: 'DC',  role: 'AR'   },
  { id: 'dc-kuldeep',        name: 'Kuldeep Yadav',         team: 'DC',  role: 'BOWL' },
  { id: 'dc-starc',          name: 'Mitchell Starc',        team: 'DC',  role: 'BOWL' },
  { id: 'dc-natarajan',      name: 'T Natarajan',           team: 'DC',  role: 'BOWL' },
  { id: 'dc-mukesh-kumar',   name: 'Mukesh Kumar',          team: 'DC',  role: 'BOWL' },
  { id: 'dc-ngidi',          name: 'Lungi Ngidi',           team: 'DC',  role: 'BOWL' },
  { id: 'dc-chameera',       name: 'Dushmantha Chameera',   team: 'DC',  role: 'BOWL' },
  { id: 'dc-jamieson',       name: 'Kyle Jamieson',         team: 'DC',  role: 'BOWL' },
  { id: 'dc-nitish-rana',    name: 'Nitish Rana',           team: 'DC',  role: 'BAT'  },
  { id: 'dc-sameer',         name: 'Sameer Rizvi',          team: 'DC',  role: 'BAT'  },
  { id: 'dc-ashutosh',       name: 'Ashutosh Sharma',       team: 'DC',  role: 'BAT'  },
  { id: 'dc-miller',         name: 'David Miller',          team: 'DC',  role: 'BAT'  },
  { id: 'dc-stubbs',         name: 'Tristan Stubbs',        team: 'DC',  role: 'BAT'  },
  { id: 'dc-nissanka',       name: 'Pathum Nissanka',       team: 'DC',  role: 'BAT'  },
  { id: 'dc-shaw',           name: 'Prithvi Shaw',          team: 'DC',  role: 'BAT'  },
  { id: 'dc-porel',          name: 'Abishek Porel',         team: 'DC',  role: 'WK'   },
  { id: 'dc-duckett',        name: 'Ben Duckett',           team: 'DC',  role: 'WK'   },
  { id: 'dc-karun',          name: 'Karun Nair',            team: 'DC',  role: 'BAT'  },
  { id: 'dc-vipraj',         name: 'Vipraj Nigam',          team: 'DC',  role: 'AR'   },
  { id: 'dc-mandal',         name: 'Ajay Mandal',           team: 'DC',  role: 'AR'   },
  { id: 'dc-vijay',          name: 'Tripurana Vijay',       team: 'DC',  role: 'AR'   },
  { id: 'dc-auqib',          name: 'Auqib Dar',             team: 'DC',  role: 'AR'   },
  { id: 'dc-madhav',         name: 'Madhav Tiwari',         team: 'DC',  role: 'AR'   },
  { id: 'dc-parakh',         name: 'Sahil Parakh',          team: 'DC',  role: 'BAT'  },

  // ── LSG – Lucknow Super Giants ────────────────────────────────────────────
  { id: 'lsg-pant',           name: 'Rishabh Pant',          team: 'LSG', role: 'WK'   },
  { id: 'lsg-pooran',         name: 'Nicholas Pooran',       team: 'LSG', role: 'WK'   },
  { id: 'lsg-markram',        name: 'Aiden Markram',         team: 'LSG', role: 'AR'   },
  { id: 'lsg-hasaranga',      name: 'Wanindu Hasaranga',     team: 'LSG', role: 'AR'   },
  { id: 'lsg-marsh',          name: 'Mitchell Marsh',        team: 'LSG', role: 'AR'   },
  { id: 'lsg-shami',          name: 'Mohammed Shami',        team: 'LSG', role: 'BOWL' },
  { id: 'lsg-mayank-yadav',   name: 'Mayank Yadav',          team: 'LSG', role: 'BOWL' },
  { id: 'lsg-mohsin',         name: 'Mohsin Khan',           team: 'LSG', role: 'BOWL' },
  { id: 'lsg-avesh',          name: 'Avesh Khan',            team: 'LSG', role: 'BOWL' },
  { id: 'lsg-nortje',         name: 'Anrich Nortje',         team: 'LSG', role: 'BOWL' },
  { id: 'lsg-badoni',         name: 'Ayush Badoni',          team: 'LSG', role: 'BAT'  },
  { id: 'lsg-samad',          name: 'Abdul Samad',           team: 'LSG', role: 'AR'   },
  { id: 'lsg-shahbaz',        name: 'Shahbaz Ahmed',         team: 'LSG', role: 'AR'   },
  { id: 'lsg-arshin',         name: 'Arshin Kulkarni',       team: 'LSG', role: 'BAT'  },
  { id: 'lsg-siddharth',      name: 'M Siddharth',           team: 'LSG', role: 'BOWL' },
  { id: 'lsg-breetzke',       name: 'Matthew Breetzke',      team: 'LSG', role: 'BAT'  },
  { id: 'lsg-inglis',         name: 'Josh Inglis',           team: 'LSG', role: 'WK'   },
  { id: 'lsg-arjun',          name: 'Arjun Tendulkar',       team: 'LSG', role: 'BOWL' },
  { id: 'lsg-mukul',          name: 'Mukul Choudhary',       team: 'LSG', role: 'WK'   },
  { id: 'lsg-digvesh',        name: 'Digvesh Rathi',         team: 'LSG', role: 'BOWL' },
  { id: 'lsg-akash',          name: 'Akash Singh',           team: 'LSG', role: 'BOWL' },
  { id: 'lsg-prince',         name: 'Prince Yadav',          team: 'LSG', role: 'AR'   },
  { id: 'lsg-naman-tiwari',   name: 'Naman Tiwari',          team: 'LSG', role: 'BOWL' },
  { id: 'lsg-akshat',         name: 'Akshat Raghuwanshi',    team: 'LSG', role: 'BAT'  },

  // ── GT – Gujarat Titans ───────────────────────────────────────────────────
  { id: 'gt-gill',           name: 'Shubman Gill',          team: 'GT',  role: 'BAT'  },
  { id: 'gt-buttler',        name: 'Jos Buttler',            team: 'GT',  role: 'WK'   },
  { id: 'gt-rashid',         name: 'Rashid Khan',           team: 'GT',  role: 'AR'   },
  { id: 'gt-siraj',          name: 'Mohammed Siraj',        team: 'GT',  role: 'BOWL' },
  { id: 'gt-rabada',         name: 'Kagiso Rabada',         team: 'GT',  role: 'BOWL' },
  { id: 'gt-prasidh',        name: 'Prasidh Krishna',       team: 'GT',  role: 'BOWL' },
  { id: 'gt-sai-sudharsan',  name: 'Sai Sudharsan',         team: 'GT',  role: 'BAT'  },
  { id: 'gt-washington',     name: 'Washington Sundar',     team: 'GT',  role: 'AR'   },
  { id: 'gt-tewatia',        name: 'Rahul Tewatia',         team: 'GT',  role: 'AR'   },
  { id: 'gt-shahrukh',       name: 'Shahrukh Khan',         team: 'GT',  role: 'BAT'  },
  { id: 'gt-phillips',       name: 'Glenn Phillips',        team: 'GT',  role: 'AR'   },
  { id: 'gt-anuj-rawat',     name: 'Anuj Rawat',            team: 'GT',  role: 'WK'   },
  { id: 'gt-kushagra',       name: 'Kumar Kushagra',        team: 'GT',  role: 'WK'   },
  { id: 'gt-banton',         name: 'Tom Banton',            team: 'GT',  role: 'BAT'  },
  { id: 'gt-holder',         name: 'Jason Holder',          team: 'GT',  role: 'AR'   },
  { id: 'gt-jayant',         name: 'Jayant Yadav',          team: 'GT',  role: 'AR'   },
  { id: 'gt-suthar',         name: 'Manav Suthar',          team: 'GT',  role: 'AR'   },
  { id: 'gt-nishant',        name: 'Nishant Sindhu',        team: 'GT',  role: 'AR'   },
  { id: 'gt-sai-kishore',    name: 'R. Sai Kishore',        team: 'GT',  role: 'BOWL' },
  { id: 'gt-ishant',         name: 'Ishant Sharma',         team: 'GT',  role: 'BOWL' },
  { id: 'gt-arshad',         name: 'Arshad Khan',           team: 'GT',  role: 'BOWL' },
  { id: 'gt-gurnoor',        name: 'Gurnoor Brar',          team: 'GT',  role: 'BOWL' },
  { id: 'gt-ashok',          name: 'Ashok Sharma',          team: 'GT',  role: 'BOWL' },
  { id: 'gt-khejroliya',     name: 'Kulwant Khejroliya',    team: 'GT',  role: 'BOWL' },

  // ── RR – Rajasthan Royals ─────────────────────────────────────────────────
  { id: 'rr-jaiswal',         name: 'Yashasvi Jaiswal',      team: 'RR',  role: 'BAT'  },
  { id: 'rr-jadeja',          name: 'Ravindra Jadeja',       team: 'RR',  role: 'AR'   },
  { id: 'rr-parag',           name: 'Riyan Parag',           team: 'RR',  role: 'AR'   },
  { id: 'rr-curran',          name: 'Sam Curran',            team: 'RR',  role: 'AR'   },
  { id: 'rr-jurel',           name: 'Dhruv Jurel',           team: 'RR',  role: 'WK'   },
  { id: 'rr-pretorius',       name: 'Lhuan-Dre Pretorius',   team: 'RR',  role: 'WK'   },
  { id: 'rr-hetmyer',         name: 'Shimron Hetmyer',       team: 'RR',  role: 'BAT'  },
  { id: 'rr-shubham-dubey',   name: 'Shubham Dubey',         team: 'RR',  role: 'BAT'  },
  { id: 'rr-vaibhav',         name: 'Vaibhav Suryavanshi',   team: 'RR',  role: 'BAT'  },
  { id: 'rr-archer',          name: 'Jofra Archer',          team: 'RR',  role: 'BOWL' },
  { id: 'rr-bishnoi',         name: 'Ravi Bishnoi',          team: 'RR',  role: 'BOWL' },
  { id: 'rr-burger',          name: 'Nandre Burger',         team: 'RR',  role: 'BOWL' },
  { id: 'rr-maphaka',         name: 'Kwena Maphaka',         team: 'RR',  role: 'BOWL' },
  { id: 'rr-sandeep',         name: 'Sandeep Sharma',        team: 'RR',  role: 'BOWL' },
  { id: 'rr-tushar',          name: 'Tushar Deshpande',      team: 'RR',  role: 'BOWL' },
  { id: 'rr-sen',             name: 'Kuldeep Sen',           team: 'RR',  role: 'BOWL' },
  { id: 'rr-yudhvir',         name: 'Yudhvir Singh Charak',  team: 'RR',  role: 'BOWL' },
  { id: 'rr-donovan',         name: 'Donovan Ferreira',      team: 'RR',  role: 'BAT'  },
  { id: 'rr-milne',           name: 'Adam Milne',            team: 'RR',  role: 'BOWL' },
  { id: 'rr-sushant',         name: 'Sushant Mishra',        team: 'RR',  role: 'BOWL' },
  { id: 'rr-aman-rao',        name: 'Aman Rao',              team: 'RR',  role: 'BOWL' },
  { id: 'rr-punja',           name: 'Yash Raj Punja',        team: 'RR',  role: 'BOWL' },
  { id: 'rr-vignesh',         name: 'Vignesh Puthur',        team: 'RR',  role: 'BOWL' },
  { id: 'rr-brijesh',         name: 'Brijesh Sharma',        team: 'RR',  role: 'BOWL' },

  // ── PBKS – Punjab Kings ───────────────────────────────────────────────────
  { id: 'pbks-shreyas-iyer', name: 'Shreyas Iyer',          team: 'PBKS', role: 'BAT'  },
  { id: 'pbks-stoinis',      name: 'Marcus Stoinis',        team: 'PBKS', role: 'AR'   },
  { id: 'pbks-maxwell',      name: 'Glenn Maxwell',         team: 'PBKS', role: 'AR'   },
  { id: 'pbks-omarzai',      name: 'Azmatullah Omarzai',    team: 'PBKS', role: 'AR'   },
  { id: 'pbks-jansen',       name: 'Marco Jansen',          team: 'PBKS', role: 'AR'   },
  { id: 'pbks-harpreet',     name: 'Harpreet Brar',         team: 'PBKS', role: 'AR'   },
  { id: 'pbks-chahal',       name: 'Yuzvendra Chahal',      team: 'PBKS', role: 'BOWL' },
  { id: 'pbks-arshdeep',     name: 'Arshdeep Singh',        team: 'PBKS', role: 'BOWL' },
  { id: 'pbks-lockie',       name: 'Lockie Ferguson',       team: 'PBKS', role: 'BOWL' },
  { id: 'pbks-prabhsimran',   name: 'Prabhsimran Singh',     team: 'PBKS', role: 'WK'   },
  { id: 'pbks-arya',          name: 'Priyansh Arya',         team: 'PBKS', role: 'BAT'  },
  { id: 'pbks-musheer',      name: 'Musheer Khan',          team: 'PBKS', role: 'AR'   },
  { id: 'pbks-wadhera',      name: 'Nehal Wadhera',         team: 'PBKS', role: 'BAT'  },
  { id: 'pbks-connolly',     name: 'Cooper Connolly',       team: 'PBKS', role: 'AR'   },
  { id: 'pbks-bartlett',     name: 'Xavier Bartlett',       team: 'PBKS', role: 'BOWL' },
  { id: 'pbks-vyshak',       name: 'Vyshak Vijaykumar',     team: 'PBKS', role: 'BOWL' },
  { id: 'pbks-dwarshuis',    name: 'Ben Dwarshuis',         team: 'PBKS', role: 'BOWL' },
  { id: 'pbks-harnoor',      name: 'Harnoor Singh Pannu',   team: 'PBKS', role: 'BAT'  },
  { id: 'pbks-vinod',        name: 'Vishnu Vinod',          team: 'PBKS', role: 'WK'   },
  { id: 'pbks-pravin',       name: 'Pravin Dubey',          team: 'PBKS', role: 'BOWL' },
  { id: 'pbks-suryansh',     name: 'Suryansh Shedge',       team: 'PBKS', role: 'AR'   },

  // ── SRH – Sunrisers Hyderabad ─────────────────────────────────────────────
  { id: 'srh-cummins',       name: 'Pat Cummins',           team: 'SRH', role: 'BOWL' },
  { id: 'srh-head',          name: 'Travis Head',           team: 'SRH', role: 'BAT'  },
  { id: 'srh-klaasen',       name: 'Heinrich Klaasen',      team: 'SRH', role: 'WK'   },
  { id: 'srh-ishan',         name: 'Ishan Kishan',          team: 'SRH', role: 'WK'   },
  { id: 'srh-abhishek',      name: 'Abhishek Sharma',       team: 'SRH', role: 'AR'   },
  { id: 'srh-nitish-reddy',  name: 'Nitish Kumar Reddy',    team: 'SRH', role: 'AR'   },
  { id: 'srh-livingstone',   name: 'Liam Livingstone',      team: 'SRH', role: 'AR'   },
  { id: 'srh-harshal',       name: 'Harshal Patel',         team: 'SRH', role: 'BOWL' },
  { id: 'srh-mavi',          name: 'Shivam Mavi',           team: 'SRH', role: 'BOWL' },
  { id: 'srh-unadkat',       name: 'Jaydev Unadkat',        team: 'SRH', role: 'BOWL' },
  { id: 'srh-kamindu',       name: 'Kamindu Mendis',        team: 'SRH', role: 'AR'   },
  { id: 'srh-carse',         name: 'Brydon Carse',          team: 'SRH', role: 'AR'   },
  { id: 'srh-edwards',       name: 'Jack Edwards',          team: 'SRH', role: 'AR'   },
  { id: 'srh-harsh-dubey',   name: 'Harsh Dubey',           team: 'SRH', role: 'BOWL' },
  { id: 'srh-verma',         name: 'Aniket Verma',          team: 'SRH', role: 'BAT'  },
  { id: 'srh-smaran',        name: 'Smaran Ravichandran',   team: 'SRH', role: 'BAT'  },
  { id: 'srh-malinga',       name: 'Eshan Malinga',         team: 'SRH', role: 'BOWL' },
  { id: 'srh-ansari',        name: 'Zeeshan Ansari',        team: 'SRH', role: 'BOWL' },
  { id: 'srh-shivang',       name: 'Shivang Kumar',         team: 'SRH', role: 'BOWL' },
  { id: 'srh-salil',         name: 'Salil Arora',           team: 'SRH', role: 'BOWL' },
  { id: 'srh-sakib',         name: 'Sakib Hussain',         team: 'SRH', role: 'BOWL' },
  { id: 'srh-tarmale',       name: 'Onkar Tarmale',         team: 'SRH', role: 'BOWL' },
  { id: 'srh-amit',          name: 'Amit Kumar',            team: 'SRH', role: 'BOWL' },
  { id: 'srh-hinge',         name: 'Praful Hinge',          team: 'SRH', role: 'BOWL' },
  { id: 'srh-fuletra',       name: 'Krains Fuletra',        team: 'SRH', role: 'BOWL' },
];
export const IPL_TEAMS = ['CSK', 'MI', 'RCB', 'KKR', 'DC', 'LSG', 'GT', 'RR', 'PBKS', 'SRH'];

export function getPlayersForMatch(team1: string, team2: string): Player[] {
  return ALL_PLAYERS.filter(p => p.team === team1 || p.team === team2);
}

export function getPlayerById(id: string): Player | undefined {
  return ALL_PLAYERS.find(p => p.id === id);
}
